{"ip": "5.139.7.167", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 1, in <module>\n    y = int(input())\nValueError: invalid literal for int() with base 10: '2^3'\n", "LastIsEmpty": false, "ErrorType": "ValueError", "CoverageInfo": [3, 2, 0, 0, 33, "2-3"], "CorrectInputs": [[["2", "2"], 1490018967]], "BadInput": ["2^3"], "UniqueId": "c2d45b0b-3fa3-4eed-d606-38d4b14d1a2d_1", "TimeStamp": 1490019088}