{"ip": "94.140.226.152", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 24, in <module>\n    a [i][j] = N\nIndexError: list index out of range\n", "LastIsEmpty": false, "ErrorType": "IndexError", "CoverageInfo": [56, 7, 30, 10, 78, "16,", "27,", "38,", "49,", "54-56,", "11->55,", "12->23,", "15->16,", "23->34,", "26->27,", "34->45,", "37->38,", "45->11,", "48->49,", "50->54"], "CorrectInputs": [[["5"], 1490678373]], "BadInput": ["3"], "UniqueId": "c2125f8e-a33d-407a-848a-a822abfe683a_0", "TimeStamp": 1490678390}