{"ip": "176.119.118.128", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 4, in <module>\n    if b[0] == 'end':\nIndexError: list index out of range\n", "LastIsEmpty": true, "ErrorType": "IndexError", "CoverageInfo": [38, 30, 24, 1, 21, "5,", "10-38,", "4->5"], "CorrectInputs": [[["1 2 -3", "end"], 1513567168]], "BadInput": ["1 2 -3", ""], "UniqueId": "c286d0ba-9f23-4900-956f-052bc315b3e6_1", "TimeStamp": 1513567132}